aurpublish(1)
=============

Name
----
aurpublish - PKGBUILD management framework for the Arch User Repository


Synopsis
--------
'aurpublish' [options] PACKAGE

'aurpublish' log [<options>] PACKAGE

'aurpublish' setup


Description
-----------
Aurpublish is an utility which helps maintainers of aur packages to submit updates.


How it works
------------
Commit PKGBUILDs in named subdirectories.
Export them to the AUR with the aurpublish command, using the subtree push
stratagem. This preserves an independent history for third-party hosting,
pull requests... ;)

Commands
--------

*setup*::
        Initialize a new repository with git hooks.

*log* <PACKAGE>::
        View the git log of a package subtree.

Options
-------

*-p* <PACKAGE>::
        Instead of publishing, pull changes from the AUR.
        Can import packages into a new subtree.

*-s*, *--speedup* <PACKAGE>::
        Speedup future publishing by recording the subtree history during
        a push. This creates a merge commit and a second copy of all
        commits in the subtree. For more details, see the "--rejoin"
        option in linkman:git-subtree[1].

*-u*, *--url* <URL>::
        Specify the URL of the server that should be used for git operations.

*-h*, *--help*::
        Prints a usage page.

Hooks
-----

*pre-commit*::
        Warn about whitespace errors, fail if checksums don't match, and
        auto-generate .SRCINFO for all changed PKGBUILDs.

*prepare-commit-msg*::
        Prefill the commit message with a list of added/updated/deleted
        packages + versions (if any).


Specifying AUR server URL
-------------------------
You can use aurpublish to interact with a git server other than the default
AUR git server at aur.archlinux.org. This may be useful if you are running
your own AUR server.

The upstream git server URL can be configured in two ways. You can set the
URL with the -u/--url options when you run aurpublish. Or you can configure
the server persistently in git by setting the aurpublish.remoteUrl option.

Set the URL with --url::
        aurpublish --url ssh://me@example.com mypackage

Set the URL for the current git directory with git config::
        git config aurpublish.remoteUrl ssh://me@example.com

Set the URL globally with git config::
        git config --global aurpublish.remoteUrl ssh://me@example.com

For more details on git options see linkman:git-config[1].


Examples
--------

aurpublish setup::
        Initialize a new repository with git hooks. Refer to Hooks section
        for more info.

aurpublish -p ansible-core-git::
        Clone existing package from aur and add its url as a git subtree to
        the currently existing git repository.

aurpublish ansible-core-git::
        Push an existing subtree to AUR.

aurpublish log::
        View the git log of a package subtree.

aurpublish --url ssh://me@example.com ansible-core-git::
        Push the subtree to a server at ssh://example.com.

AUTHORS
-------
Eli Schwartz <eschwartz@archlinux.org>
